// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/codehouse-hero/Cinematic.tsx": () => import("../components/mockups/codehouse-hero/Cinematic.tsx"),
  "./components/mockups/codehouse-hero/Current.tsx": () => import("../components/mockups/codehouse-hero/Current.tsx")
};
